version: "3.7"
services:

  sphinx-index:
    image: hellotalk/sphinxsearch:latest
    container_name: "sphinx-index"
    volumes:
      - "/path/to/sphinx-docker/sphinx.conf:/usr/local/sphinx/etc/sphinx.conf"
      - "/path/to/sphinx-docker/data:/usr/local/sphinx/var/data"
      - "/path/to/sphinx-docker/log:/usr/local/sphinx/var/log"
    command: ["/usr/local/sphinx/bin/indexer", "--rotate", "--all"]

  sphinx-searchd:
    image: hellotalk/sphinxsearch:latest
    depends_on:
      - sphinx-index
    ports:
      - "8306:9306"
      - "8312:9312"
    volumes:
      - "/path/to/sphinx-docker/sphinx.conf:/usr/local/sphinx/etc/sphinx.conf"
      - "/path/to/sphinx-docker/data:/usr/local/sphinx/var/data"
      - "/path/to/sphinx-docker/log:/usr/local/sphinx/var/log"
    container_name: "sphinx-searchd"
    restart: on-failure
    command: ["searchd", "--nodetach", "--config", "/usr/local/sphinx/etc/sphinx.conf"]
